alias: Zásuvka ručně vypnuta během události
trigger:
  - platform: state
    entity_id: switch.smart_plug  # ← nahraď podle sebe
    to: 'off'
condition:
  - condition: state
    entity_id: calendar.tvuj_kalendar  # ← nahraď podle sebe
    state: 'on'
  - condition: state
    entity_id: input_boolean.zasuvka_zapnuta_automatizaci  # ← nahraď
    state: 'on'
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.zasuvka_vypnuta_rucne
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.zasuvka_zapnuta_automatizaci
mode: single
